#version 430

layout(binding=0, std430)buffer VertexIDs{ uint vertexIDs[]; };

layout(local_size_x=8, local_size_y=8, local_size_z=8)in;

void main() {
    const uint xDim = 32 * 3;
    const uint dim = 32;
    const uint index = gl_GlobalInvocationID.z * xDim * dim +
    gl_GlobalInvocationID.y * xDim +
    gl_GlobalInvocationID.x * 3;

    vertexIDs[index]     = 0;
    vertexIDs[index + 1] = 0;
    vertexIDs[index + 2] = 0;
}